# Generated by Django 4.2.6 on 2023-12-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Farmers/img')),
            ],
        ),
    ]
